### PR TITLE
updated frontend and backend to work with operator

### PR DESCRIPTION
**Pull request by Gkrumbach07**
## Related Issues and Dependencies

https://github.com/thoth-station/odh-dashboard/issues/7

## This introduces a breaking change

- No

## This Pull Request implements

Frontend Changes
- package picker now is more strict. it uses annotations to autofill but those can only be edited but not removed. packages can also be added however.
- build image has os inputs now
- update image only works if image exists (not just crd)
- update image allows to enable and disable annotations but not add or edit
- renaming and folder structure changes

backend changes
- cre route exists. it only posts, gets, and deletes.... cannot edit cre yet
- image route now only gets, updates, and deletes.... should not create imagestreams from scratch
- new types

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
This was kind of tested but not fully as i could not get the operator to deploy. I did find some error [here](https://github.com/thoth-station/meteor-operator/blob/main/controllers/cnbi/controller.go#L208-L216) when a packageList buildType is used. it was an error with structs and arrays in go? Not sure if thats my environment or not.

feel free to ping me

**Comment by codificat** [comment]
Thanks for this!

I tested it in my test cluster. In particular, I focused on adding a new image through importing it (i.e. the "BYON" use case). Some initial observations:
- the dashboard was missing permissions to access CustomNBImage resources. I had to patch the odh-dashboard role for this to work(*)
- the dashboard correctly created a CustomNBImage resource for the image import (yay!)
- however, the UI failed to correctly show the CR status as the pipeline progressed
- it also failed to show the results of the imported image, i.e. after the import pipeline succeeded (and correctly added software and package annotations to the created ImageStream) and the cnbi CR was correctly updated to `Succeeded`, the list of notebook images still shows its status as *?* and the package details are empty:

imatge


(*) I manually added this to the `odh-dashboard` role:

```yaml
- apiGroups:
  - meteor.zone
  resources:
  - customnbimages
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```

**Comment by harshad16** [comment]
@codificat  shall we merge this PR and release the odh-dashboard? 
then we can update the roles and odh-dashboard version in the odh-manifests.

**Comment by codificat** [comment]
I think it's not a good idea to merge in its current state: it actually breaks some functionality, like showing the contents of custom images or their status.

Fixing the role could be done in this PR as well (there are role definitions in `manifests/base/`)

On the other hand, if you think it's better to merge and fix the problems later we can discuss that - only after today's demo though; let's not release a broken dashboard just now.

**Comment by harshad16** [comment]
ack, thanks for the note
let's wait, as you said.

**Comment by codificat** [comment]
It's looking better! :+1: 

I tested the current version and things mostly work: I can create and delete CRE objects, and status is reported correctly.

A couple of problems I found:
- When adding a package (e.g while editing the fields when going to build a new image), the resulting CRE always has the same version specifier, `==`, regardless of what you select there
- Also, the version and version specifier should be optional when adding a package. A user might want to add a package by name (only) without having to add a version specifier
- I see multiple errors in the JS console while in the "create from existing image" page. One of them has bad consequences: when I select to build on top of a previously-imported image, the page goes completely blank

Here is the error I see in the console before it goes blank:

```
Uncaught TypeError: child.props.value is undefined
    item Select.js:538
    getDisplay Select.js:538
    render Select.js:840
    React 16
    setValue AddNewImageForm.tsx:232
    onSelect ExisitingImageForm.tsx:239
    onClick SelectOption.js:123
    React 23
    <anonymous> index.tsx:16
    tsx app.bundle.js:8764
    __webpack_require__ app.bundle.js:12692
    <anonymous> app.bundle.js:13851
    <anonymous> app.bundle.js:13855
Select.js:538
```

but as mentioned, there are a few more (`Maximum update depth exceeded` repeats multiple times)

**Comment by codificat** [comment]
Tested and looking great, thanks!
/lgtm
/approve

I'm not sure what happened to the pre-commit check though, prow reports it as *aborted*...
/retest

**Pull request merged**
