### PR TITLE
Rebase onto v2.5.2

### LINKED ISSUE #10: Rebase from upstream
We should rebase this fork to catch up with the changes upstream.

One potential rebase target could be the most recent tag/release from upstream. At the time of this writing, this is https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.5.2

### PR DESCRIPTION
**Pull request by Gkrumbach07**
## Related Issues and Dependencies
 
fixes: https://github.com/thoth-station/odh-dashboard/issues/10

also related to https://github.com/thoth-station/odh-dashboard/issues/11

## This introduces a breaking change

- No

## This Pull Request implements

rebase onto tag [v2.5.2](https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.5.2) of upstream

### Description

also fixed sorting

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
Questioning if I did this rebase correctly.
Also in the process of creating a new cluster so this may or may not work.

**Comment by codificat** [comment]
Thanks for this!

> Questioning if I did this rebase correctly

It looks good to me: comparing with upstream, this is how our changes look after this rebase:

```
$ git hist upstream/main.. --no-merges
* 837db05a 2022-12-13 | ui fixes [Gage Krumbach]
* c28dd71f 2022-12-07 | added fixes and ui changes [Gage Krumbach]
* 9afc57f0 2022-12-01 | Fixed connection to operator (test-rebase) [Gage Krumbach]
* 108cffb8 2022-11-30 | Rename Custom Notebook Image to Custom Runtime Environment [Pep Turró Mauri]
* 99741511 2022-11-30 | Add permissions to interact with CRE resources [Pep Turró Mauri]
* 1f20d830 2022-11-17 | updated frontend and backend to work with operator [Gage Krumbach]
* 208ca3dd 2022-10-24 | Switched from BYON to CNBI mockup [Gage Krumbach]
| * 9b3e5b52 2022-11-04 | Add basic pre-commit configuration for prow [Pep Turró Mauri]
|/  
* ce575998 2022-10-21 | Enable auto build on tag release for thoth odh-dashboard dev [Harshad Reddy Nalla]
* dfec9b1b 2022-12-15 | fixed sorting [Gage Krumbach]
* ec61d48f 2022-12-13 | ui fixes [Gage Krumbach]
* a2890dc6 2022-12-07 | added fixes and ui changes [Gage Krumbach]
* 73cbde61 2022-12-01 | Fixed connection to operator [Gage Krumbach]
* b17eee29 2022-11-30 | Rename Custom Notebook Image to Custom Runtime Environment [Pep Turró Mauri]
* 27b84adf 2022-11-30 | Add permissions to interact with CRE resources [Pep Turró Mauri]
* 297b82c6 2022-11-17 | updated frontend and backend to work with operator [Gage Krumbach]
* 1a79d610 2022-10-24 | Switched from BYON to CNBI mockup [Gage Krumbach]
* 1e714288 2022-11-04 | Add basic pre-commit configuration for prow [Pep Turró Mauri]
* f37c93fc 2022-10-21 | Enable auto build on tag release for thoth odh-dashboard dev [Harshad Reddy Nalla]
```

> Also in the process of creating a new cluster so this may or may not work.

I tested it in my test cluster. I am still hitting #12 - mostly with Firefox, but I now also had it happen on Chromium. That problem seems unrelated to the rebase to me (it was there before), but I would like to test this a bit more before merging...

**Comment by codificat** [comment]
The rebase looks good now, and the problem with the TypeError seems to be gone, thanks!

One question though: should we move the new *git repo* addition to a separate PR, just for clarity?

**Comment by Gkrumbach07** [comment]
> One question though: should we move the new git repo addition to a separate PR, just for clarity?

I rolled it back

git feature is here: https://github.com/thoth-station/odh-dashboard/pull/14/files

**Comment by codificat** [comment]
/lgtm
/approve

thanks!

**Pull request merged**
